name: 01-building-blocks

on:
    push:
        branches:
            - main

jobs:
    my-first-job:
        runs-on: windows-latest
        steps:
          - name: Allow scripts to run
            shell: powershell
            run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
            
          - name: My First Job
            run: echo "My first job is running!"
            